helmDefaults:
  atomic: true
  wait: true
  createNamespace: false

releases:
  - name: '{{ env "RELEASE_NAME" | default "hilars-dev" }}'
    namespace: hilars-prod
    chart: ./chart
    values:
      - image: registry.hilars.dev/hilars-dev/landing:latest
      - ingress:
          url: hilars.dev
          redirect_wwww: true
